version: "3.3"
services:

 app:
   build: .
   container_name: mssh
   volumes:
    - "./:/work"
   working_dir: "/work"
   environment:
     - UID=1000
     - GID=1000
     - POS_TOKEN_SECRECT=adjkewrew23aewdfpooe23
   restart: always
   links:
     - transltr:transltr

 transltr:
   image: libretranslate/libretranslate
   restart: always
   volumes:
     #- "./translate_models:/root/.local/share/argos-translate"
     - "./translate_models:/root/.local/share/LibreTranslate"
     
